### PR TITLE
Refine our articulation of the problem

### PR DESCRIPTION
**Pull request by dcwalk**
This sets up a discussion on refining our problem statement, moving from #23:

Thoughts from previous work:
> I feel like this is part of the problem, but I don't see any of the challenges that gave rise to EDGI archiving work, challenges from community science, etc... that I think also inform why people are interested in DT?

On linking to `model.md`
> I think this fits, but I'm a bit leery of "problem" repeated here a bunch without being able to reference the problem space :)

### CODE REVIEW

**Comment by ebarry** [comment]
This sounds great @ebenp 
@flyingzumwalt interested to hear your thoughts on the above comment here

**Comment by mhucka** [comment]
I concur with @ebarry, FWIW.

**Comment by dcwalk** [comment]
Me too!

**Comment by flyingzumwalt** [comment]
This PR has gotten out of sync with the master branch in a strange way (looks like the content of the PR is actually already merged into the master branch). This makes it hard to understand what's being proposed/discussed and what it would mean to approve and merge this PR. I am going to merge it and then suggest changes in new PRs. @ebenp and @ebarry could you re-submit your suggestions as PRs?

**Pull request merged**
